# Generated by Django 4.2.1 on 2023-05-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_actor_category_director_genre_permissions_user_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='video',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('FullHD', 'fullhd'), ('HD', 'hd'), ('SD', 'sd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='../static/profile_pictures/8.png', upload_to='user/<django.db.models.fields.CharField>', verbose_name='profile picture'),
        ),
    ]
