# Generated by Django 4.2.1 on 2023-06-13 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_collections_options_alter_movie_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('SD', 'sd'), ('HD', 'hd'), ('FullHD', 'fullhd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Canceled', 'canceled'), ('Not released', 'not released')], default='Not released', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('loading', 'loading'), ('disinformation', 'disinformation'), ('other', 'other'), ('quality', 'quality'), ('unacceptable content', 'unacceptable content'), ('error', 'error')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Erza Scarlet', max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_picture/6.jpg', upload_to='user', verbose_name='profile picture'),
        ),
    ]
