# Generated by Django 4.2.1 on 2023-05-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_movie_file_alter_movie_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='categories',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mainapp.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('FullHD', 'fullhd'), ('HD', 'hd'), ('SD', 'sd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('unacceptable content', 'unacceptable content'), ('other', 'other'), ('quality', 'quality'), ('disinformation', 'disinformation'), ('loading', 'loading'), ('error', 'error')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='../static/profile_pictures/10.png', upload_to='user/<django.db.models.fields.CharField>', verbose_name='profile picture'),
        ),
    ]
