# Generated by Django 4.2.1 on 2023-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_movie_quality_alter_ticket_problem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='manga',
            field=models.URLField(blank=True, null=True, verbose_name='manga url'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratingIMDB',
            field=models.FloatField(blank=True, null=True, verbose_name='rating IMDB'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratingKP',
            field=models.FloatField(blank=True, null=True, verbose_name='rating KP'),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Canceled', 'canceled'), ('Not released', 'not released')], default='Not released', max_length=50, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.movie', verbose_name='history'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('HD', 'hd'), ('SD', 'sd'), ('FullHD', 'fullhd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('quality', 'quality'), ('loading', 'loading'), ('disinformation', 'disinformation'), ('unacceptable content', 'unacceptable content'), ('error', 'error'), ('other', 'other')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='../static/profile_pictures/5.png', upload_to='user/<django.db.models.fields.CharField>', verbose_name='profile picture'),
        ),
    ]
