# Generated by Django 4.2.1 on 2023-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_movie_quality_alter_movie_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='actors', verbose_name='actor picture'),
        ),
        migrations.AddField(
            model_name='director',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='directors', verbose_name='actor picture'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='position',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('HD', 'hd'), ('FullHD', 'fullhd'), ('SD', 'sd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Not released', 'not released'), ('Canceled', 'canceled'), ('Published', 'published')], default='Not released', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('loading', 'loading'), ('error', 'error'), ('unacceptable content', 'unacceptable content'), ('disinformation', 'disinformation'), ('other', 'other'), ('quality', 'quality')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='../static/profile_pictures/7.png', upload_to='user/<django.db.models.fields.CharField>', verbose_name='profile picture'),
        ),
    ]
