# Generated by Django 4.2.1 on 2023-06-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_replies_dislikes_replies_likes_review_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratingAP',
            field=models.FloatField(blank=True, default=0, verbose_name='rating AnimePlay'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('loading', 'loading'), ('disinformation', 'disinformation'), ('quality', 'quality'), ('other', 'other'), ('unacceptable content', 'unacceptable content'), ('error', 'error')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Levi Ackerman', max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_picture/9.jpg', upload_to='user', verbose_name='profile picture'),
        ),
    ]
