# Generated by Django 4.2.1 on 2023-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_category_options_category_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(default='movies/pictures/poster.jpg', upload_to='movies/pictures', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='relesased',
            field=models.IntegerField(verbose_name='released year'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('disinformation', 'disinformation'), ('loading', 'loading'), ('other', 'other'), ('error', 'error'), ('quality', 'quality'), ('unacceptable content', 'unacceptable content')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='../static/profile_pictures/7.png', upload_to='user/<django.db.models.fields.CharField>', verbose_name='profile picture'),
        ),
    ]
