# Generated by Django 4.2.1 on 2023-06-19 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_collections_author_alter_feedback_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('FullHD', 'fullhd'), ('SD', 'sd'), ('HD', 'hd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Not released', 'not released'), ('Canceled', 'canceled'), ('Published', 'published')], default='Not released', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('disinformation', 'disinformation'), ('error', 'error'), ('unacceptable content', 'unacceptable content'), ('loading', 'loading'), ('quality', 'quality'), ('other', 'other')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Goku Son', max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_picture/7.jpg', upload_to='user', verbose_name='profile picture'),
        ),
    ]
