# Generated by Django 4.2.1 on 2023-05-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_movie_quality_alter_movie_relesased_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='relesased',
            new_name='released',
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('HD', 'hd'), ('FullHD', 'fullhd'), ('SD', 'sd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Canceled', 'canceled'), ('Not released', 'not released')], default='Not released', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('loading', 'loading'), ('unacceptable content', 'unacceptable content'), ('other', 'other'), ('disinformation', 'disinformation'), ('error', 'error'), ('quality', 'quality')], max_length=200, verbose_name='problem type'),
        ),
    ]
