# Generated by Django 4.2.1 on 2023-06-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_news_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscomment',
            old_name='createad',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('disinformation', 'disinformation'), ('unacceptable content', 'unacceptable content'), ('other', 'other'), ('loading', 'loading'), ('quality', 'quality'), ('error', 'error')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Kanade Tachibana', max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_picture/9.jpg', upload_to='user', verbose_name='profile picture'),
        ),
    ]
