# Generated by Django 4.2.1 on 2023-06-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_feedback_status_alter_movie_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('SD', 'sd'), ('FullHD', 'fullhd'), ('HD', 'hd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Not released', 'not released'), ('Canceled', 'canceled')], default='Not released', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='dislikes',
            field=models.IntegerField(blank=True, null=True, verbose_name='dislikes'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='likes',
            field=models.IntegerField(blank=True, null=True, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('loading', 'loading'), ('quality', 'quality'), ('other', 'other'), ('unacceptable content', 'unacceptable content'), ('disinformation', 'disinformation'), ('error', 'error')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Sakura Haruno', max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_picture/2.jpg', upload_to='user', verbose_name='profile picture'),
        ),
    ]
