# Generated by Django 4.2.1 on 2023-06-24 00:00

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_user_favourites_alter_movie_quality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='from_who',
            field=models.ManyToManyField(blank=True, null=True, related_name='from_who', to=settings.AUTH_USER_MODEL, verbose_name='from_who'),
        ),
        migrations.AddField(
            model_name='message',
            name='has_seen',
            field=models.BooleanField(default=False, verbose_name='has seen'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_whom',
            field=models.ManyToManyField(blank=True, null=True, related_name='to_whom', to=settings.AUTH_USER_MODEL, verbose_name='to_whom'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('answered', 'Answered'), ('opened', 'Opened')], default='opened', max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('SD', 'sd'), ('FullHD', 'fullhd'), ('HD', 'hd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Canceled', 'canceled'), ('Not released', 'not released'), ('Published', 'published')], default='Not released', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('quality', 'quality'), ('disinformation', 'disinformation'), ('unacceptable content', 'unacceptable content'), ('loading', 'loading'), ('other', 'other'), ('error', 'error')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Rias Gremory', max_length=254, verbose_name='name'),
        ),
    ]
