# Generated by Django 4.2.1 on 2023-06-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_movie_options_alter_feedback_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('answered', 'Answered')], default='opened', max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Not released', 'not released'), ('Published', 'published'), ('Canceled', 'canceled')], default='Not released', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('other', 'other'), ('disinformation', 'disinformation'), ('error', 'error'), ('unacceptable content', 'unacceptable content'), ('quality', 'quality'), ('loading', 'loading')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourites', to='mainapp.movie', verbose_name='favourites'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Edward Elric', max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_picture/10.jpg', upload_to='user', verbose_name='profile picture'),
        ),
    ]
