# Generated by Django 4.2.1 on 2023-06-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_alter_feedback_status_alter_movie_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='background',
            field=models.ImageField(default='movies/pictures/poster.jpg', upload_to='movies/pictures', verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('HD', 'hd'), ('SD', 'sd'), ('FullHD', 'fullhd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('other', 'other'), ('error', 'error'), ('loading', 'loading'), ('unacceptable content', 'unacceptable content'), ('disinformation', 'disinformation'), ('quality', 'quality')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Asuna Yuuki', max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_picture/3.jpg', upload_to='user', verbose_name='profile picture'),
        ),
    ]
