# Generated by Django 4.2.1 on 2023-06-30 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_movie_background_alter_movie_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='disliked',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked', to=settings.AUTH_USER_MODEL, verbose_name='disliked'),
        ),
        migrations.AddField(
            model_name='review',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to=settings.AUTH_USER_MODEL, verbose_name='liked'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('SD', 'sd'), ('FullHD', 'fullhd'), ('HD', 'hd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Not released', 'not released'), ('Canceled', 'canceled'), ('Published', 'published')], default='Not released', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('disinformation', 'disinformation'), ('unacceptable content', 'unacceptable content'), ('error', 'error'), ('quality', 'quality'), ('other', 'other'), ('loading', 'loading')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Holo', max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_picture/8.jpg', upload_to='user', verbose_name='profile picture'),
        ),
    ]
