# Generated by Django 4.2.1 on 2023-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_remove_review_dislikes_remove_review_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('answered', 'Answered'), ('opened', 'Opened')], default='opened', max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('FullHD', 'fullhd'), ('SD', 'sd'), ('HD', 'hd')], default='SD', max_length=50, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Not released', 'not released'), ('Canceled', 'canceled'), ('Published', 'published')], default='Not released', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.CharField(choices=[('quality', 'quality'), ('unacceptable content', 'unacceptable content'), ('error', 'error'), ('disinformation', 'disinformation'), ('other', 'other'), ('loading', 'loading')], max_length=200, verbose_name='problem type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Monkey D. Luffy', max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_picture/1.jpg', upload_to='user', verbose_name='profile picture'),
        ),
    ]
